homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_time_zone

  customize: !include_dir_merge_named customize
#  customize: !include customize.yaml
  customize_glob:
    "sensor.dark_sky_*":
      homebridge_hidden: true
  packages: !include_dir_named packages

zone:
  - name: ScienceLogic
    latitude: !secret sciencelogic_latitude
    longitude: !secret sciencelogic_longitude
    radius: 500
    icon: mdi:briefcase

#introduction:
frontend:
#  javascript_version: latest

discovery:

logbook:
  exclude:
    entities:
      - sensor.since_last_boot
      - sensor.since_last_boot_templated
      - sensor.time
      - sensor.date
      - sensor.ha_uptime

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - cover

  exclude:
    entities:
     - sensor.last_boot
     - sensor.since_last_boot
    #  - sensor.since_last_boot_templated
    #  - sensor.uptime
     - sensor.ha_uptime
     - sensor.date
     - sensor.time

cloud:

config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret duckdns_url

# Checks for available updates
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables a map showing the location of tracked devices
map:

ios: 

#ifttt:
#  key: !secret ifttt_key

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

sun:

light:
  - platform: hue
#    host: 10.0.1.92

hue:
  bridges:
    - host: 10.0.1.21
      filename: phue.conf
      allow_unreachable: true
      allow_hue_groups: false

august:
  login_method: email
  username: !secret august_username
  password: !secret august_password

media_player:
  - platform: denonavr
  - platform: plex

# remote:
#   - platform: harmony
#     name: Living Room TV

nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
#  binary_sensors:
#    monitored_conditions:
#      - 'fan'

climate:
  platform: nest

device_tracker:
#  - platform: unifi_direct
- platform: unifi
#  host: raspberrypi.local
  username: !secret unifi_username
  password: !secret unifi_password
  verify_ssl: false
#  track_new_devices: no

# Text to speech
tts:
  - platform: google

group: !include_dir_merge_named groups
# group: !include groups.yaml

# device_tracker: !include_dir_merge_list device_tracker

sensor: !include_dir_merge_list sensor

# automation: !include_dir_merge_list automation
# automation: !include automations.yaml

# scene: !include_dir_merge_list scene

# switch: !include_dir_merge_list switch

# script: !include_dir_merge_named script
script: !include scripts.yaml

# input_boolean: !include_dir_merge_named input_boolean
input_boolean: !include input_boolean.yaml

# shell_command: !include_dir_merge_named shell_command


